server:
  port: 8762
spring:
  application:
    name: nativeconfigserver
  profiles:
    active: native
#    表示配置文件的获取方式 native 本地获取
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
#          本地配置文件的存放路径